### ISSUE TITLE
Validation for Invalid Appointment Dates

### ISSUE THREAD

**Issue by BerreDelikara** [dilaydal/-VIS-Vehicle-Inspection-System-#3]
Appointments should not allow the following invalid date inputs:
Dates earlier than the current date.
Dates where:
Month (MM) exceeds 12.
Day (DD) exceeds the valid number of days for the selected month.

**Comment by sevvaleraslan** [comment]
this issue is handled with [fff67b673c9ae5dc6013fb3c08f70450ebacf9e8](https://github.com/dilaydal/-VIS-Vehicle-Inspection-System-/commit/fff67b673c9ae5dc6013fb3c08f70450ebacf9e8)
