### ISSUE TITLE
Manager Frame Operations Needs Order

### ISSUE THREAD

**Issue by dilaydal** [dilaydal/-VIS-Vehicle-Inspection-System-#4]
Update/Add/Remove mechanic options needs to be reorganized under Manage Mechanic.

**Comment by egeoruc** [comment]
The issue has been resolved with commit [c89c77cad0c180e8f7fc3ecadb6d9e9962d45edc](https://github.com/dilaydal/-VIS-Vehicle-Inspection-System-/commit/375234876cd8f063fc105281328559a57a93d0c2#diff-131d0e7622ab533bdcbc887eca4de1975ca2c556902511fbee98a67612b675b1)
